### PR TITLE
Recorder.configure: don't overwrite plugins unless specified

### PR DESCRIPTION
**Pull request by MarSoft**
With most options, Recorder.configure() doesn't touch the value if corresponding option is not passed.
But with `plugins` option behaviour is different: it is updated every time you call `configure`.
So this code won't work correctly:

    xray_recorder.configure(plugins=('EC2Plugin', 'ECS'))
    ...
    xray_recorder.configure(context=MyContext())  # this resets plugins

This patch will fix that behaviour: now in order to explicitly reset plugins, you will need to pass an empty tuple to `configure`;
if `plugins is None` then plugin list won't be changed.

### CODE REVIEW

**Comment by haotianw465** [comment]
What do you thing of doing this:

```python
         if plugins:
             plugin_modules = get_plugin_modules(plugins)
             for module in plugin_modules:
                 module.initialize()
             self._plugins = plugin_modules
```

**Comment by MarSoft** [comment]
This approach makes it impossible to remove previously added plugins.

**Comment by MarSoft** [comment]
I.e. it will only change plugins list if at least one plugin is specified, with no option to pass empty list (which will be just ignored). Hence I added "is None" check.

**Comment by haotianw465** [comment]
OK make sense.

**Comment by haotianw465** [comment]
Could you also add a line on `CHANGELOG` under "unreleased" section.

**Comment by MarSoft** [comment]
Done

**Pull request merged**
