### PR TITLE
Only run integration tests on master.

### PR DESCRIPTION
**Pull request by anuraaga**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by srprash — APPROVED** [review]

**Comment by anuraaga** [comment]
This pr obviously doesn't change build logic so something seems to have made the build red, guessing unpinned dependencies. @srprash @lupengamzn is it something you could look at?

**Comment by awssandra** [comment]
Can we also change the branch name to "main"? Remove non-inclusive wording if you see it :)

**Comment by anuraaga** [comment]
Github has added support for renaming relatively smoothly, including migrating open PRs, it's just the workflows that may need to be updated. It's probably a good time to go ahead and do it for all our repos indeed.

**Comment by srprash** [comment]
> This pr obviously doesn't change build logic so something seems to have made the build red, guessing unpinned dependencies. @srprash @lupengamzn is it something you could look at?

SQLAlchemy tests are failing due to some changes in the latest version of the library. We would need to pin its version for some of the python version tests. @lupengamzn is taking a look.

**Comment by lupengamzn** [comment]
> This pr obviously doesn't change build logic so something seems to have made the build red, guessing unpinned dependencies. @srprash @lupengamzn is it something you could look at?

The issue should be [fixed](https://github.com/aws/aws-xray-sdk-python/pull/275/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449R21-R22) now by pinning the version of [SQLAlchemy](https://pypi.org/project/SQLAlchemy/) and [Flask-SQLAlchemy](https://pypi.org/project/Flask-SQLAlchemy/) for test.

**Review by bhautikpip — APPROVED** [review]

**Pull request merged**
