### PR TITLE
Fix UnboundLocalError when aiohttp server raises a CancelledError

### PR DESCRIPTION
**Pull request by armisael**
*Issue #, if available:* N/A

*Description of changes:* In `aiohttp` middleware, catch `BaseException` instead of `Exception` to avoid `UnboundLocalError`.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by carolabadeer — COMMENTED** [review]
Looks good so far. Can you please provide a code snippet that causes an `UnboundLocalError` to be raised just for reference?

**Comment by armisael** [comment]
I'm not sure, unfortunately. We have a proxy to some external services, to serve as a cache; such proxy uses aiohttp, and connects to both REST (with httpx) and SOAP (with zeep) services; we recently upgraded from python 3.6 to 3.10 and this error happened once; it's still not clear to me what exactly caused the `CancelledError`.

**Review by carolabadeer — APPROVED** [review]

**Review by carolabadeer — CHANGES_REQUESTED** [review]
Merged main into this branch and now some CI tests are failing - can you please take a look?

**Comment by carolabadeer** [comment]
@srprash thank you for pointing that out! Looks good to merge now that the issue is fixed.
@armisael sorry for the confusion

**Review by carolabadeer — APPROVED** [review]

**Pull request merged**
