### PR TITLE
Support dbname and database kwarg in psycopg2.connect()

### PR DESCRIPTION
**Pull request by IlyaSukhanov**
*Issue #90 

*Description of changes:
~~psycopg2.connect() Supports 3 variants of operation:~~
 1. ~~psycopg2.connect("dbname=test user=postgres password=secret")~~
 2. ~~psycopg2.connect(dbname="test", user="postgres", password="secret")~~
 3. ~~psycopg2.connect()~~

~~Previously we only supported 1 and 2. Now support variant 3 and mix of 2 and 3.~~

~~This change is not entierly backwards compatible previously the metadata used to
contain keys `url` and `user`. These are no longer exposed however the connection
parameters are available as `connection_string`. If this backward incompatibility
is not desirable then change can be made to extract values as they were before
using conn.dsn. However the URL will not be correct as password is mangled. It's
not clear to me if one option is clearly better than the other.~~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by IlyaSukhanov** [comment]
[Looks like the fields do matter](https://github.com/aws/aws-xray-sdk-python/pull/83/files/d3fc58e3bf10becceea814a15d3ed73f88084f15#r213794779). I'll adjust PR to rebuild them of `conn.dsn()`

**Comment by IlyaSukhanov** [comment]
Made change backwards compatible.

**Comment by Tankanow** [comment]
👍 I like this improvement.

**Comment by haotianw465** [comment]
Thank you for the contribution. This improvement looks good to me. I think it is a miss on unit test where some use cases are not covered https://github.com/aws/aws-xray-sdk-python/blob/master/tests/ext/psycopg2/test_psycopg2.py. Do you mind adding more common use cases in the test to prevent regression?

**Comment by haotianw465** [comment]
Thank you for your contribution. I have merged this PR and will prepare a release soon.

**Pull request merged**
